# TODO:
# - [ ] use default species across all time and space: sardine (since motivated creation of CalCOFI; see https://en.wikipedia.org/wiki/CalCOFI)

# Install librarian if needed
if (!requireNamespace("librarian", quietly = TRUE)) {
  install.packages("librarian")
}

# Load libraries
# remotes::install_github("bbest/mapgl@fix-compare-widget-parity", force=T) # https://github.com/walkerke/mapgl/pull/187
# remotes::install_github("calcofi/calcofi4r", force = T)
librarian::shelf(
  bslib,
  bsicons,
  calcofi / calcofi4r,
  conductor,
  data.tree,
  DBI,
  dplyr,
  DT,
  duckdb,
  geosphere,
  ggplot2,
  glue,
  here,
  highcharter,
  htmltools,
  htmlwidgets,
  httr2,
  jsonlite,
  leaflet,
  litedown,
  lubridate,
  mapgl,
  plotly,
  purrr,
  readr,
  sf,
  shiny,
  shinyWidgets,
  stringr,
  thematic,
  tibble,
  tidyr,
  zip,
  quiet = TRUE
)

# variables ----
hex_geo <- here("data/hex.geojson")
cache_dir <- here("app/app_cache")
debug <- interactive() || nzchar(Sys.getenv("RSTUDIO")) # TRUE in console or Posit IDE
is_tour_on <- !debug # turn off while debugging

# database connection ----
# pre-built by prep_db.R with materialized bio_obs, env_obs, H3 tables
db_path <- Sys.getenv("CALCOFI_DB", here("data/calcofi_latest.duckdb"))
if (!file.exists(db_path)) {
  # fall back to most recent calcofi_*.duckdb in data/
  db_candidates <- list.files(
    here("data"),
    "^calcofi_v.*\\.duckdb$",
    full.names = TRUE
  )
  if (length(db_candidates) > 0) {
    db_path <- sort(db_candidates, decreasing = TRUE)[1]
  } else {
    stop("No database found. Run prep_db.R first.")
  }
}
message("Using database: ", db_path)
drv <- duckdb(dbdir = db_path, read_only = TRUE)
con <- dbConnect(drv)
dbExecute(con, "LOAD h3;")
dbExecute(con, "LOAD spatial;")
# dbListTables(con) |> sort()

# load hexagons (pre-generated by prep_db.R)
sf_hex <- st_read(hex_geo, quiet = TRUE)

# spatial layers registry ----
d_spatial_layers <- read_csv(
  here("../workflows/metadata/spatial_layers.csv"),
  show_col_types = FALSE
)
# pmtiles_base_url <- "https://file.calcofi.io/_spatial"
pmtiles_base_url <- "https://storage.googleapis.com/calcofi-files-public/_spatial"

# gcloud storage buckets describe gs://calcofi-files-public --format="/Users/bbest/Github/CalCOFI/int-app/data/_cors_file.json"
# cd ~/Github/CalCOFI/int-app/data
# gcloud storage buckets update gs://calcofi-files-public --cors-file=_cors_file.json

# load functions ----
source(here("app/functions.R"))

# extract species names and date range ----
# all species (ichthyo + invert) are in the species table with WoRMS taxonomy
sp_names <- tbl(con, "species") |>
  left_join(
    tbl(con, "taxon") |>
      filter(authority == "WoRMS"),
    by = join_by(worms_id == taxonID)
  ) |>
  mutate(
    rank_part = ifelse(
      is.na(taxonRank) | taxonRank == "",
      "",
      paste0(tolower(taxonRank), ": ")),
    name_part = ifelse(
      is.na(common_name) | common_name == "",
      "",
      paste0(common_name, " ")),
    name = paste0(name_part, "(", rank_part, scientific_name, ")")
  ) |>
  pull(name) |>
  sort()

bio_date_rng <- tbl(con, "bio_obs") |>
  summarize(
    date_min = min(time_start, na.rm = TRUE) |> as.Date(),
    date_max = max(time_start, na.rm = TRUE) |> as.Date()
  ) |>
  collect() |>
  as.vector()

env_date_rng <- tbl(con, "env_obs") |>
  summarize(
    date_min = min(datetime_utc, na.rm = TRUE) |> as.Date(),
    date_max = max(datetime_utc, na.rm = TRUE) |> as.Date()
  ) |>
  collect() |>
  as.vector()

min_max_date <- c(
  min(bio_date_rng[[1]], env_date_rng[[1]]),
  max(bio_date_rng[[2]], env_date_rng[[2]])
)

# global constants ----
default_sp_name <- "Pacific sardine (pilchard) (species: Sardinops sagax)"
default_max_hours_diff <- 6
default_max_meters_diff <- 2000

ts_res_choices <- list(
  "Year" = "year",
  "Quarter" = "quarter",
  "Year, Quarter" = "year_quarter"
)

env_var_choices <- list(
  "Temperature (\u00baC)" = "temperature",
  "Salinity (PSS-78)" = "salinity",
  "Oxygen (\u00b5mol/kg)" = "oxygen_umol_kg",
  "Phosphate (\u00b5mol/L)" = "phosphate",
  "Silicate (\u00b5mol/L)" = "silicate",
  "Nitrite (\u00b5mol/L)" = "nitrite",
  "Nitrate (\u00b5mol/L)" = "nitrate",
  "Chlorophyll-a (\u00b5g/L)" = "chlorophyll_a",
  "Phaeopigment (\u00b5g/L)" = "phaeopigment",
  "Dynamic Height (m)" = "dynamic_height",
  "Sigma-theta (kg/m\u00b3)" = "sigma_theta",
  "Pressure (dbar)" = "pressure",
  "PAR (\u00b5E/m\u00b2/s)" = "par",
  "pH" = "ph",
  "Ammonia (\u00b5mol/L)" = "ammonia"
)

env_stat_choices <- list(
  "Avg." = "mean",
  "Max" = "max",
  "Min" = "min",
  "Std. Dev." = "sd"
)

# mapping variables ----
min_res <- 1
max_res <- 10
res_range <- min_res:max_res
zoom_breaks <- seq(1, 13, length.out = length(res_range) + 1)
zoom_breaks[1] <- 0
zoom_breaks[length(zoom_breaks)] <- 22

# tour ----
tour <- Conductor$new(
  exitOnEsc = T,
  keyboardNavigation = T
)$step(
  title = "Welcome",
  text = "The app is initializing with a map comparing Pacific sardine larvae
    and temperature collected on CalCOFI cruises since 1949.<br><br>
    (To exit tour, use keyboard esc button)",
  buttons = list(
    list(
      action = "next",
      text = "Next"
    )
  )
)$step(
  el = "#sel_data",
  title = "Select Filters",
  text = "You can change the species and environmental selection here, along with
    temporal and spatial constraints.",
  buttons = list(
    list(
      action = "back",
      text = "Back"
    ),
    list(
      action = "next",
      text = "Done"
    )
  )
)

# cleanup on exit ----
onStop(function() {
  dbDisconnect(con, shutdown = TRUE)
})
